name: Test Beta SSH

on:
  workflow_dispatch:

jobs:
  test-beta-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Check SSH port
        run: |
          nc -vz -w 10 "${{ secrets.BETA_PAYARA_INSTANCE_HOST }}" 22
