name: Test Beta SSH

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    paths:
      - '.github/workflows/test-beta-ssh.yml'

jobs:
  test-beta-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Check SSH port
        run: |
          nc -vz -w 10 "${{ secrets.BETA_PAYARA_INSTANCE_HOST }}" 22
